name: CI/CD with Docker


on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make application.yml
        run: |
          sudo mkdir -p ./bookduck/src/main/resources # 디렉토리가 없으면 생성
          cd ./bookduck/src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: Make GCP Service Account Key
        run: |
          mkdir -p /home/ubuntu/bookduck/src/main/resources
          cd /home/ubuntu/bookduck/src/main/resources
          echo "${{ secrets.GCP_ACCESS_KEY_BASE64 }}" | base64 --decode > mmc-bookduck-ocr.json
        shell: bash

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          cd ./bookduck
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push
        uses: docker/build-push-action@v6
        with:
          context: ./bookduck
          file: ./bookduck/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker-compose -f /home/ubuntu/docker-compose.yml down # 이전 컨테이너들 제거
            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest # 최신 Docker 이미지 가져오기
            sudo docker-compose -f /home/ubuntu/docker-compose.yml up -d # docker-compose로 컨테이너 실행
            sudo docker image prune -f # 불필요한 이미지를 정리

